/** @type {import('@lhci/cli').Config} */
module.exports = {
  ci: {
    collect: {
      staticDistDir: './dist',
      url: [
        'http://localhost/index.html',
        'http://localhost/about/index.html',
        'http://localhost/dashboard/index.html',
        'http://localhost/resume/index.html',
        'http://localhost/projects/recursive-engine/index.html',
        'http://localhost/gallery/index.html',
        'http://localhost/consult/index.html',
        'http://localhost/architecture/index.html',
        'http://localhost/omega/index.html',
        'http://localhost/github-pages/index.html',
        'http://localhost/products/index.html',
        'http://localhost/community/index.html',
        'http://localhost/essays/index.html',
        'http://localhost/404.html',
        'http://localhost/projects/aetheria-rpg/index.html',
        'http://localhost/projects/agentic-titan/index.html',
        'http://localhost/projects/ai-conductor/index.html',
        'http://localhost/projects/ai-council/index.html',
        'http://localhost/projects/block-warfare/index.html',
        'http://localhost/projects/community-infrastructure/index.html',
        'http://localhost/projects/distribution-strategy/index.html',
        'http://localhost/projects/eight-organ-system/index.html',
        'http://localhost/projects/generative-music/index.html',
        'http://localhost/projects/knowledge-base/index.html',
        'http://localhost/projects/life-my-midst-in/index.html',
        'http://localhost/projects/linguistic-atomization/index.html',
        'http://localhost/projects/metasystem-master/index.html',
        'http://localhost/projects/narratological-lenses/index.html',
        'http://localhost/projects/orchestration-hub/index.html',
        'http://localhost/projects/org-architecture/index.html',
        'http://localhost/projects/public-process/index.html',
        'http://localhost/projects/public-record-data-scrapper/index.html',
        'http://localhost/projects/the-actual-news/index.html',
        'http://localhost/projects/your-fit-tailored/index.html',
      ],
      numberOfRuns: 1,
    },
    assert: {
      assertions: {
        'categories:performance': ['error', { minScore: 0.85 }],
        'categories:accessibility': ['error', { minScore: 0.90 }],
        'categories:best-practices': ['warn', { minScore: 0.90 }],
        'categories:seo': ['warn', { minScore: 0.90 }],
        'first-contentful-paint': ['warn', { maxNumericValue: 2000 }],
        'largest-contentful-paint': ['warn', { maxNumericValue: 3000 }],
        'cumulative-layout-shift': ['warn', { maxNumericValue: 0.1 }],
      },
    },
    upload: {
      target: 'filesystem',
      outputDir: '.lighthouseci',
    },
  },
};
