#!/usr/bin/env node
// scripts/shibui-extract.mjs
// Parses 21 project .astro pages and emits one YAML stub per project.
// Idempotent: skips any slug whose YAML already exists.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PAGES_DIR = path.join(__dirname, '../src/pages/projects');
const OUTPUT_DIR = path.join(__dirname, '../src/data/shibui/projects');

// ─── helpers ────────────────────────────────────────────────────────────────

/** slug from filename: "aetheria-rpg.astro" → "aetheria-rpg" */
function fileToSlug(filename) {
	return path.basename(filename, '.astro');
}

/** Convert a heading string to a safe YAML key slug. */
function headingToSlug(heading) {
	return heading
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/(^-|-$)/g, '');
}

/**
 * Strip all HTML/Astro tags and replace template expressions with [dynamic].
 * Returns plain text.
 */
function stripTags(raw) {
	// Replace {…} template expressions first
	let text = raw.replace(/\{[^}]*\}/g, '[dynamic]');
	// Remove self-closing components like <Cite …/> <abbr …/>
	text = text.replace(/<[A-Za-z][^>]*\/>/g, '');
	// Remove opening/closing tags
	text = text.replace(/<[^>]+>/g, '');
	// Collapse whitespace
	text = text.replace(/\s+/g, ' ').trim();
	return text;
}

/**
 * Extract the value of a prop from a ProjectLayout opening tag.
 * Handles both:  title="Foo"  and  title={`Foo`}
 */
function extractProp(tagContent, propName) {
	// String literal: title="..."
	const strMatch = tagContent.match(new RegExp(`${propName}="([^"]*)"`, 's'));
	if (strMatch) return strMatch[1].trim();

	// Template literal: title={`...`}  — build regex without backtick in template
	const tplPattern = `${propName}=\\{` + '`([^`]*)' + '`\\}';
	const tplMatch = tagContent.match(new RegExp(tplPattern, 's'));
	if (tplMatch) return tplMatch[1].trim();

	return '';
}

/**
 * Parse the body of an .astro project page.
 * Returns { title, tagline, sections: [{heading, paragraphs: string[]}] }
 */
function parsePage(source) {
	// ── extract ProjectLayout opening tag ───────────────────────────────────
	// The tag can span multiple lines and ends at > (after which comes the body)
	const layoutMatch = source.match(/<ProjectLayout[\s\S]*?>/);
	let title = '';
	let tagline = '';
	if (layoutMatch) {
		const tag = layoutMatch[0];
		title = extractProp(tag, 'title');
		tagline = extractProp(tag, 'tagline');
	}

	// ── extract section headings + following paragraphs ─────────────────────
	// Strip frontmatter (between --- markers)
	const withoutFrontmatter = source.replace(/^---[\s\S]*?---\n/, '');

	const sections = [];
	// Match h2 headings; capture text between > and </h2>
	const h2Regex = /<h2>([\s\S]*?)<\/h2>/g;
	let match;
	const headingPositions = [];

	while ((match = h2Regex.exec(withoutFrontmatter)) !== null) {
		headingPositions.push({
			heading: stripTags(match[1]),
			index: match.index + match[0].length,
		});
	}

	for (let i = 0; i < headingPositions.length; i++) {
		const { heading, index } = headingPositions[i];
		const end =
			i + 1 < headingPositions.length
				? headingPositions[i + 1].index - headingPositions[i + 1].heading.length - 20
				: withoutFrontmatter.length;

		const section = withoutFrontmatter.slice(index, end);

		// Extract <p>…</p> blocks
		const pRegex = /<p>([\s\S]*?)<\/p>/g;
		const paragraphs = [];
		let pMatch;
		while ((pMatch = pRegex.exec(section)) !== null) {
			const plain = stripTags(pMatch[1]);
			if (plain.length > 10) paragraphs.push(plain);
		}

		if (paragraphs.length > 0) {
			sections.push({ heading, paragraphs });
		}
	}

	return { title, tagline, sections };
}

// ─── YAML serialisation (no external dep) ──────────────────────────────────

/** Escape a string for YAML double-quoted scalar. */
function yamlStr(s) {
	return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

/** Produce the YAML content for one project. */
function buildYaml(slug, title, tagline, sections) {
	const lines = [];
	lines.push(`# Shibui content — ${slug}`);
	lines.push('# Generated by shibui:extract. Edit entry text, then remove [DRAFT] markers.');
	lines.push(`page: projects/${slug}`);
	lines.push(`title: "${yamlStr(title)}"`);
	lines.push(`tagline: "${yamlStr(tagline)}"`);
	lines.push('sections:');

	for (const { heading, paragraphs } of sections) {
		const hSlug = headingToSlug(heading);
		lines.push(`  - heading: "${yamlStr(heading)}"`);
		lines.push('    units:');

		paragraphs.forEach((text, idx) => {
			const unitId = `${slug}.${hSlug}.p${idx + 1}`;
			const preview = text.slice(0, 80).replace(/"/g, '\\"');
			lines.push(`      - id: "${unitId}"`);
			lines.push(`        elevated_preview: "${preview}${text.length > 80 ? '...' : ''}"`);
			lines.push(`        entry: "[DRAFT]"`);
		});
	}

	lines.push('');
	return lines.join('\n');
}

// ─── main ───────────────────────────────────────────────────────────────────

async function main() {
	fs.mkdirSync(OUTPUT_DIR, { recursive: true });

	const files = fs
		.readdirSync(PAGES_DIR)
		.filter((f) => f.endsWith('.astro'))
		.sort();

	let generated = 0;
	let skipped = 0;

	for (const file of files) {
		const slug = fileToSlug(file);
		const outPath = path.join(OUTPUT_DIR, `${slug}.yaml`);

		if (fs.existsSync(outPath)) {
			console.log(`  skip  ${slug} (already exists)`);
			skipped++;
			continue;
		}

		const source = fs.readFileSync(path.join(PAGES_DIR, file), 'utf8');
		const { title, tagline, sections } = parsePage(source);

		if (!title) {
			console.warn(`  warn  ${slug} — could not extract title, writing stub anyway`);
		}

		const yaml = buildYaml(slug, title, tagline, sections);
		fs.writeFileSync(outPath, yaml, 'utf8');
		console.log(`  write ${slug} (${sections.length} sections)`);
		generated++;
	}

	console.log(`\nDone. Generated: ${generated}, Skipped: ${skipped}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
